##### Diagonal Diffrence

absolue |Sum(Right Diaogonal) - Sum(Left Diaogonal)|

In [12]:
import math
import os
import random
import re
import sys
import numpy as np

In [13]:
def diagonalDifference(arr):
    prim =0
    sec=0
    length = len(arr[0])
    for count in range(length):
        prim += arr[count][count]
        sec += arr[count][(length-count-1)]
    return abs(prim-sec)

In [14]:
arr = [
[11,2,4],
[4,5,6],
[10,8,-12],
]

result = diagonalDifference(arr)
print(result)

15


In [16]:
arr =  np.arange(3, 12).reshape(3,3)
print(arr)
  
result = diagonalDifference(arr)
print(result)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
0


In [25]:
arr = [random.randint(1, 10) for i in range(0, 9)]
arr = np.array(arr).reshape(3,3)
print(arr)
result = diagonalDifference(arr)
print(result)

[[10  1  3]
 [ 1  7  7]
 [ 4  2  9]]
12
